### ISSUE TITLE
Support for bpmn20 and  bpmn20.xml files

### ISSUE THREAD

**Issue by noble-bhaskar** [shlaikov/intellij-bpmn2-plugin#11]
Right now the plugin supports *.bpmn files.

It will be good if support is added for ***.bpmn20** and  ***.bpmn20.xml**  files

**Comment by temofey1989** [comment]
+1

**Comment by temofey1989** [comment]
Really looking forward to the release of this feature. 😃

**Comment by temofey1989** [comment]
Thanks a lot! 😉

**Comment by noble-bhaskar** [comment]
@shlaikov Thank you so much for the quick support
