### ISSUE TITLE
Does not support IntelliJ 233.*

### ISSUE THREAD

**Issue by dlastov** [shlaikov/intellij-bpmn2-plugin#19]
Wouldn't it be better to remove the highest version restriction from the plugin manifest and add it only when it is known that the plugin is not compatible any more?

**Comment by shlaikov** [comment]
@dlastov Initially, I used a ready-made template, which set the final supported version by default. I will be more than happy, if there is such an opportunity. I'll study this issue.

**Comment by dlastov** [comment]
It seems to be documented here:

https://plugins.jetbrains.com/docs/intellij/plugin-configuration-file.html#idea-plugin__idea-version

> until-build (optional)
> 
> The highest IDE version compatible with the plugin. Undefined value declares compatibility with all the IDEs since the version specified by the since-build (also with the future builds what may cause incompatibility errors).

The `until-build` is optional.  I think, if it should happen one day that it will not be compatible anymore, and Idea will detect an exception in the plugin after the upgrade, so it will automatically disable the plugin, which will be acceptable behaviour, basically as now, just less often, because I assume that mostly it will stay compatible.

**Comment by shlaikov** [comment]
@dlastov hello! The plugin has already been updated, you can check it. If everything is fine, close the issue, please.
